export { Home } from "./Home/Home"
export { QuizCategory } from "./QuizCategory/QuizCategory"
export { Quiz } from "./Quiz/Quiz"
export { Result } from "./Result/Result"
export { Login } from "./Login/Login"
export { Signup } from "./Signup/Signup"